
-- Create archive_photos table
CREATE TABLE IF NOT EXISTS public.archive_photos (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    photo_url text not null,
    title text not null,
    description text,
    taken_at date default CURRENT_DATE
);

-- Enable RLS
ALTER TABLE public.archive_photos ENABLE ROW LEVEL SECURITY;

-- Policies for public access (similar to alumnae table)
CREATE POLICY "Enable read access for all users"
ON public.archive_photos FOR SELECT
USING (true);

CREATE POLICY "Enable insert for all users"
ON public.archive_photos FOR INSERT
WITH CHECK (true);

CREATE POLICY "Enable update for all users"
ON public.archive_photos FOR UPDATE
USING (true);

CREATE POLICY "Enable delete for all users"
ON public.archive_photos FOR DELETE
USING (true);
