
-- Create gatherings table
CREATE TABLE IF NOT EXISTS public.gatherings (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    title text not null,
    type text,
    status text check (status in ('planning', 'open', 'upcoming', 'done')),
    date text,
    location text,
    participants int default 0
);

-- Enable RLS
ALTER TABLE public.gatherings ENABLE ROW LEVEL SECURITY;

-- Policies for public access (similar to other tables)
CREATE POLICY "Enable read access for all users"
ON public.gatherings FOR SELECT
USING (true);

CREATE POLICY "Enable insert for all users"
ON public.gatherings FOR INSERT
WITH CHECK (true);

CREATE POLICY "Enable update for all users"
ON public.gatherings FOR UPDATE
USING (true);

CREATE POLICY "Enable delete for all users"
ON public.gatherings FOR DELETE
USING (true);
