-- Enable UUID extension if needed (not strictly required for this schema but good practice)
-- create extension if not exists "uuid-ossp";

-- Create the 'alumnae' table
create table if not exists alumnae (
  id bigint generated by default as identity primary key,
  name text not null,
  cohort int4 not null,
  region text,
  job text,
  company text,
  tags text[],
  email text,
  phone text,
  introduction text,
  birthday text, -- Format: 'MM-DD'
  payment_status text default 'unpaid', -- 'paid' or 'unpaid'
  created_at timestamptz default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS) - Optional but recommended
-- alter table alumnae enable row level security;

-- Create a policy that allows everything for now (Public Access)
-- warning: NOT SECURE for production. For demo only.
-- create policy "Enable all access for all users" on alumnae for all using (true) with check (true);

-- Comment:
-- Since we are using the 'anon' key on the client side without authentication, 
-- we typically need to enable RLS and add a policy to allow public operations, 
-- OR disable RLS (easier for prototype).
-- By default, new tables might have RLS disabled or enabled depending on project settings.
-- If you see "permission denied" errors, run:
-- alter table alumnae disable row level security;
